version: '3.7'
services:

  mysql:
      image: mysql:8.0
      command: mysqld --default-authentication-plugin=mysql_native_password
      ports:
        - 3302:3306
      environment:
          MYSQL_DATABASE: YOUR_DB_NAME
          MYSQL_USER: YOUR_DB_USER_NAME
          MYSQL_PASSWORD: YOUR_DB_PASSWORD
          MYSQL_ROOT_PASSWORD: YOUR_DB_PASSWORD
      volumes:
        - mysql:/var/lib/mysql
  
  phpmyadmin:
      image: phpmyadmin/phpmyadmin:5.1.0
      links:
          - mysql:db
      ports:
          - 8001:80
      depends_on:
        - mysql

  django:
    build: .
    volumes:
      - django-log:/usr/src/app/log
      # - django-media:/usr/src/app/media
      - django-static:/usr/src/app/assets
    env_file: 
      - path: .env
    ports:
      - 8000:8000
    depends_on:
      - mysql
    links:
        - mysql:db

  web:
    image: nginx:1.16.0-alpine
    restart: always
    volumes:
      # - django-media:/usr/src/app/media
      - django-static:/usr/src/app/assets
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
    depends_on:
      - django


volumes:
  mysql:
    external: true
  django-log:
  # django-media:
  django-static:
