# Generated by Django 4.2.13 on 2024-06-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IgPost",
            fields=[
                (
                    "shortcode",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("owner_id", models.CharField(max_length=30)),
                ("content", models.TextField(blank=True, null=True)),
                ("date", models.DateField()),
                ("location_id", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "location_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "location_city",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("counrty", models.CharField(max_length=30)),
                ("has_location", models.IntegerField(blank=True, null=True)),
            ],
            options={"db_table": "IgPost", "managed": False,},
        ),
        migrations.CreateModel(
            name="CityInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city_name", models.CharField(max_length=30)),
                ("city_name_ch", models.CharField(max_length=30)),
                ("image", models.URLField(blank=True, null=True)),
            ],
            options={"db_table": "CityInfo",},
        ),
    ]
