# Generated by Django 4.2.13 on 2024-06-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0002_iglocation"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location_name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
            ],
            options={"db_table": "LocationMap",},
        ),
    ]
