# Generated by Django 4.2.13 on 2024-06-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0003_locationmap"),
    ]

    operations = [
        migrations.AddField(
            model_name="cityinfo",
            name="description",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
